## Numpy 

In [1]:
import numpy as np 

In [2]:
np.__version__

'1.24.4'

In [3]:
#pip install numpy

In [4]:
import sys
sys.version

'3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]'

In [5]:
my_list =[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
#np.
# No developer uses entire function 
#Situation based learning 

In [7]:
type(my_list)

list

In [8]:
arr=np.array(my_list)

In [9]:
arr

array([0, 1, 2, 3, 4, 5])

In [10]:
type(arr)

numpy.ndarray

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
!pip install --upgrade numpy


In [14]:
!pip install --upgrade scipy


In [15]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [17]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(20,10)

array([], dtype=int32)

In [20]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [21]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [22]:
np.arange(10,30,2,3)

TypeError: Cannot interpret '3' as a data type

In [23]:
np.zeros(3) #Parameter, as system default parameters are taken 

array([0., 0., 0.])

In [24]:
np.zeros(3, dtype=int)  # Hyperparameter because we assigned the parameter 

array([0, 0, 0])

In [25]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [26]:
np.zeros([2,2], dtype=int)

array([[0, 0],
       [0, 0]])

In [27]:
np.ones(2)

array([1., 1.])

In [28]:
np.ones([25,4], dtype=int)  # Row X Column 10 by 4 matrix 

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [29]:
np.twos(2)

AttributeError: module 'numpy' has no attribute 'twos'

## Random and Ranndint

In [30]:
random(3,2)

NameError: name 'random' is not defined

In [31]:
random.rand(3,2)

NameError: name 'random' is not defined

In [32]:
np.random.rand(3,2)

array([[0.66118254, 0.83710236],
       [0.36486925, 0.92194932],
       [0.0118148 , 0.02184731]])

In [33]:
np.random.randint(2) # low inclusiec and high exclusive write 1 random number 

0

In [34]:
np.random.randint(4) # it will generate 1 random no from between 0 to 4 4 exclusive 

3

In [35]:
np.random.randint(1,8) # Generate random nos between 1 to 8

2

In [36]:
np.random.randint(1,8,4) # Generate 4 random numbers between 1 to 8

array([7, 2, 6, 7])

In [37]:
np.random.randint(1,8,100) 

array([1, 2, 7, 1, 3, 3, 2, 2, 7, 5, 7, 1, 1, 2, 2, 1, 7, 6, 1, 7, 5, 6,
       3, 4, 2, 3, 1, 1, 3, 7, 3, 4, 5, 4, 1, 5, 3, 6, 7, 5, 1, 4, 1, 5,
       3, 3, 4, 7, 5, 7, 7, 2, 1, 7, 1, 4, 4, 3, 6, 5, 6, 5, 7, 4, 7, 5,
       5, 2, 6, 3, 4, 6, 1, 2, 4, 4, 3, 7, 6, 5, 5, 4, 4, 1, 6, 7, 3, 1,
       7, 6, 5, 1, 5, 7, 4, 1, 7, 4, 3, 4])

In [38]:
np.random.randint(10,40,(10,10)) #10X10 matric of random with no between 10 and 40

array([[27, 28, 13, 28, 38, 19, 25, 19, 10, 29],
       [27, 38, 31, 35, 16, 13, 24, 12, 14, 21],
       [11, 13, 30, 27, 36, 22, 32, 38, 34, 22],
       [12, 17, 32, 16, 24, 36, 22, 32, 26, 38],
       [34, 21, 12, 27, 38, 28, 12, 13, 38, 25],
       [10, 36, 36, 10, 17, 34, 37, 33, 28, 17],
       [32, 11, 10, 33, 18, 14, 29, 39, 27, 30],
       [27, 14, 32, 25, 18, 19, 38, 35, 10, 16],
       [22, 10, 33, 39, 18, 15, 14, 16, 26, 30],
       [39, 15, 38, 13, 17, 34, 30, 22, 13, 26]])

In [39]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
np.arange(1,13).reshape(3,5) # 15 elemets are requierd, hence error 

ValueError: cannot reshape array of size 12 into shape (3,5)

In [42]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## Slicing in matrix 

In [43]:
b=np.random.randint(10,20,(5,4))
b

array([[10, 13, 18, 15],
       [19, 14, 12, 18],
       [10, 15, 19, 13],
       [17, 13, 18, 18],
       [11, 16, 15, 10]])

In [44]:
b[:]

array([[10, 13, 18, 15],
       [19, 14, 12, 18],
       [10, 15, 19, 13],
       [17, 13, 18, 18],
       [11, 16, 15, 10]])

In [45]:
b[0] # Gives the first row

array([10, 13, 18, 15])

In [46]:
b[0:5] # Prints zero to 4 rows 

array([[10, 13, 18, 15],
       [19, 14, 12, 18],
       [10, 15, 19, 13],
       [17, 13, 18, 18],
       [11, 16, 15, 10]])

In [47]:
b[0,1] # Zeroth row and first column RXC How to find a specific column in a aarray 

13

In [48]:
b[::-1] # Rows sequence is reversed

array([[11, 16, 15, 10],
       [17, 13, 18, 18],
       [10, 15, 19, 13],
       [19, 14, 12, 18],
       [10, 13, 18, 15]])

In [49]:
b[::-2] # Reverse me rows print karega 2 ke steps me 

array([[11, 16, 15, 10],
       [10, 15, 19, 13],
       [10, 13, 18, 15]])

In [50]:
print(b[::-2])

[[11 16 15 10]
 [10 15 19 13]
 [10 13 18 15]]


In [51]:
b

array([[10, 13, 18, 15],
       [19, 14, 12, 18],
       [10, 15, 19, 13],
       [17, 13, 18, 18],
       [11, 16, 15, 10]])

In [52]:
b[-3,-3]

15

In [53]:
b.max()

19

In [54]:
b.min()

10

In [55]:
b.mean()

14.7

In [56]:
b

array([[10, 13, 18, 15],
       [19, 14, 12, 18],
       [10, 15, 19, 13],
       [17, 13, 18, 18],
       [11, 16, 15, 10]])

In [57]:
# How to find columns
b[:,0]

array([10, 19, 10, 17, 11])

In [58]:
b[:,1]

array([13, 14, 15, 13, 16])

In [59]:
b[0:5, 0:6]

array([[10, 13, 18, 15],
       [19, 14, 12, 18],
       [10, 15, 19, 13],
       [17, 13, 18, 18],
       [11, 16, 15, 10]])

In [60]:
b[2:3, 0:2]

array([[10, 15]])

In [61]:
b[1:]

array([[19, 14, 12, 18],
       [10, 15, 19, 13],
       [17, 13, 18, 18],
       [11, 16, 15, 10]])

## Masking 

In [62]:
np.arange(10,20).reshape(10,100)

ValueError: cannot reshape array of size 10 into shape (10,100)

In [63]:
b.dtype

dtype('int32')

In [68]:
l=[1, 2.3j]

In [69]:
arr=np.array(l)

In [70]:
arr

array([1.+0.j , 0.+2.3j])

In [71]:
arr.dtype

dtype('complex128')