In [1]:
import numpy as np 

In [4]:
l=[10,20,13,255,36,15]

In [3]:
np.array([10,20,13,255,36,15])

array([ 10,  20,  13, 255,  36,  15])

In [5]:
a=np.array(l)

In [6]:
type(a)

numpy.ndarray

In [7]:
type(np.array([10,20,13,255,36,15]))

numpy.ndarray

In [8]:
a

array([ 10,  20,  13, 255,  36,  15])

In [10]:
# 2D matrix 

arr=np.array([[45,34,22,2],[24,55,3,22]])
arr

array([[45, 34, 22,  2],
       [24, 55,  3, 22]])

## dtype

In [11]:
np.array(l, dtype=float)

array([ 10.,  20.,  13., 255.,  36.,  15.])

In [12]:
np.array(l, dtype=bool)

array([ True,  True,  True,  True,  True,  True])

In [13]:
np.array(l, dtype=complex)

array([ 10.+0.j,  20.+0.j,  13.+0.j, 255.+0.j,  36.+0.j,  15.+0.j])

## arange

In [14]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [15]:
np.arange(1,25,2) #strides---> alternate numbers 

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

## reshape

In [16]:
#the product of both the numbers should be equal to no of items present inside the array

In [18]:
np.arange(1,11).reshape(5,2) # Rows by columns We have 5 rows and 2 columns 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
np.arange(1,11).reshape(2,5) # 2 rows and 5 columns 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## ones and zeroes 

we can initialise the values 

In [22]:
np.ones((3,4)) # We have to mention the size inside a tuple 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## random

In [28]:
np.random.random((4,3))

array([[0.15940392, 0.89956082, 0.15864009],
       [0.3156799 , 0.90939618, 0.41265588],
       [0.0397632 , 0.61956373, 0.55394987],
       [0.24338188, 0.46923687, 0.2533413 ]])

In [31]:
np.random.random((4,3))

array([[0.67994468, 0.45223282, 0.45521434],
       [0.8007021 , 0.24044852, 0.46899955],
       [0.61392086, 0.08023232, 0.87240947],
       [0.98441721, 0.79770697, 0.74515955]])

## linspace

It is also called as Linearly space , Linearly separable,in a given range at equal distance it 
creates points. 

In [33]:
np.linspace(-10,10,10) # Lower range, upper range and no of items 

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [37]:
np.linspace(2,26,7)

array([ 2.,  6., 10., 14., 18., 22., 26.])

## identity

identity matrix is that diagnol items will be ones and everything else will be zeroes

In [38]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## array Attributes 

In [43]:
a1=np.arange(10) # Nos from 0 to 10 
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a2=np.arange(12, dtype=float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [52]:
a3=np.arange(8, dtype=float).reshape(2,2,2) # 3D ---> Tensor 
a3

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

This here is an tensor

## ndim

In [47]:
a1.ndim

1

In [48]:
a2.ndim

2

In [51]:
a3.ndim

3

## shape

gives the no of rowas and columns

In [53]:
a1.shape

(10,)

In [54]:
a2.shape

(3, 4)

In [55]:
a3.shape

(2, 2, 2)

## size

gives the total no of items 

In [56]:
a1.size

10

In [57]:
a2.size

12

In [58]:
a3.size

8

## item size

it gives the memory occupied by the item

In [59]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a1.itemsize # bytes

4

In [62]:
a2.itemsize

8

In [63]:
a3.itemsize

8

In [64]:
a3

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

## dtype

gies datatype of all items 

In [66]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
float64


In [72]:
m=[1,1.2,True]

In [73]:
am=np.array(m)

In [74]:
am

array([1. , 1.2, 1. ])

In [75]:
am.dtype

dtype('float64')

## changing the Data Type

In [77]:
x=np.array([33,22,5.6])
x

array([33. , 22. ,  5.6])

In [78]:
x.astype(int)

array([33, 22,  5])

In [79]:
x.astype(float)

array([33. , 22. ,  5.6])

In [84]:
m=np.array([1,1.2,True, 1+2j])
m

array([1. +0.j, 1.2+0.j, 1. +0.j, 1. +2.j])

In [85]:
z=m.astype(int)
z

<ipython-input-85-0a435ea62820>:1: ComplexWarning: Casting complex values to real discards the imaginary part
  z=m.astype(int)


array([1, 1, 1, 1])

## Array Operations 

In [87]:
z1=np.arange(12).reshape(3,4)
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
z2=np.arange(12,24).reshape(3,4)
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## scalar operations 

scalar operations on numpy arrays include performing addition or subtraction or multiplication on each element of a numpy array 

In [90]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
z1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [92]:
z1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [93]:
z1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [95]:
z1**2 # Power 

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [96]:
# Modulus
z1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [97]:
z1/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [98]:
z1//2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]], dtype=int32)

## relational operators 

The relational operators are also known as the comparison operators, their main function is to return either a true or a false based on the value o foperands 

In [99]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [100]:
z2>2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [101]:
z2>20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

## Vector opeartion 

2 numpy arrays are required for this 

In [102]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [104]:
z1+z2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [105]:
z1*z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [106]:
z1-z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [107]:
z1/z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [109]:
y1=np.arange(6).reshape(3,2)
y2=np.arange(6).reshape(2,3)


In [110]:
y1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [111]:
y2

array([[0, 1, 2],
       [3, 4, 5]])

In [112]:
y1+y2

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [113]:
y1*y2

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [114]:
# if dimenstions are different, vector operations do not work

## Array Functions

In [116]:
k1=np.random.random((3,3))
k1

array([[0.13949591, 0.42510121, 0.2881863 ],
       [0.29566722, 0.71884296, 0.69318787],
       [0.91548019, 0.58733091, 0.33917524]])

In [117]:
np.round(k1*100)

array([[14., 43., 29.],
       [30., 72., 69.],
       [92., 59., 34.]])

In [118]:
np.max(k1)

0.9154801912399275

In [119]:
np.min(k1)

0.13949591113487614

In [120]:
np.prod(k1)

0.00045916761929465496

### in numpy, 0= columns and 1= rows

In [122]:
# if we want maximum of every row 

np.max(k1, axis=1)

array([0.42510121, 0.71884296, 0.91548019])

In [124]:
# if we want maximum of every column 
np.max(k1, axis=0)

array([0.91548019, 0.71884296, 0.69318787])

In [125]:
# Product of every column 
np.prod(k1, axis=0)

array([0.0377584 , 0.17947717, 0.0677561 ])

## Statistics related function 

In [126]:
#mean 
k1

array([[0.13949591, 0.42510121, 0.2881863 ],
       [0.29566722, 0.71884296, 0.69318787],
       [0.91548019, 0.58733091, 0.33917524]])

In [127]:
np.mean(k1)

0.4891630902539564

In [128]:
# mean of every column 
k1.mean(axis=0)

array([0.45021444, 0.57709169, 0.44018314])

In [129]:
#median
np.median(k1)

0.4251012109894229

In [130]:
#standard Deviation 

np.std(k1)

0.23862147719540985

In [131]:
np.std(k1, axis=0)

array([0.33511345, 0.12013793, 0.18010833])

In [132]:
np.var(k1)

0.0569402093789195

In [133]:
np.var(k1, axis=0)

array([0.11230102, 0.01443312, 0.03243901])